import React from 'react'

function Reviews() {
  return (
    <div className="container">
      <div className="reviews">
        <b>This is only for checking the react page is refreshing or not when this component is fired</b> <br></br>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi molestiae illum quidem inventore ipsum ipsa reiciendis quam accusantium in architecto, minus, laborum sequi debitis sunt recusandae veniam non, minima velit!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis ducimus, maiores, nemo ipsam in eveniet aspernatur natus nostrum deleniti dolor aliquam excepturi pariatur, omnis ipsa assumenda amet facilis sequi doloribus!Lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam quo rerum commodi eveniet doloremque. Itaque rem, suscipit ab ipsa quia vitae dignissimos placeat ad maxime culpa. Quia quod similique expedita. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates, nam corrupti illum eum veritatis quod accusantium voluptate perferendis vel excepturi sit autem exercitationem soluta voluptatem facere aperiam veniam illo. Accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat quam et in, a, vel dignissimos atque delectus reprehenderit veritatis amet praesentium minima provident id iste deserunt beatae est. Nemo, officia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore dolorem impedit qui et veniam aperiam corrupti dicta cupiditate nihil culpa rem architecto aliquam reiciendis ratione, amet velit itaque error corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic cumque esse repellendus, minus facere laudantium, autem voluptate pariatur molestiae vitae quod cupiditate non minima magni iure sunt molestias ullam iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi omnis, laboriosam fugit atque dolorem perferendis ipsam totam pariatur laborum sint voluptatem beatae exercitationem optio aperiam maxime recusandae unde sit? Earum?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi molestiae illum quidem inventore ipsum ipsa reiciendis quam accusantium in architecto, minus, laborum sequi debitis sunt recusandae veniam non, minima velit!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis ducimus, maiores, nemo ipsam in eveniet aspernatur natus nostrum deleniti dolor aliquam excepturi pariatur, omnis ipsa assumenda amet facilis sequi doloribus!Lorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam quo rerum commodi eveniet doloremque. Itaque rem, suscipit ab ipsa quia vitae dignissimos placeat ad maxime culpa. Quia quod similique expedita. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates, nam corrupti illum eum veritatis quod accusantium voluptate perferendis vel excepturi sit autem exercitationem soluta voluptatem facere aperiam veniam illo. Accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat quam et in, a, vel dignissimos atque delectus reprehenderit veritatis amet praesentium minima provident id iste deserunt beatae est. Nemo, officia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore dolorem impedit qui et veniam aperiam corrupti dicta cupiditate nihil culpa rem architecto aliquam reiciendis ratione, amet velit itaque error corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic cumque esse repellendus, minus facere laudantium, autem voluptate pariatur molestiae vitae quod cupiditate non minima magni iure sunt molestias ullam iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi omnis, laboriosam fugit atque dolorem perferendis ipsam totam pariatur laborum sint voluptatem beatae exercitationem optio aperiam maxime recusandae unde sit? Earum?
      </div>
    </div>
  )
}

export default Reviews
